### ISSUE TITLE
PDFs of schematics?

### ISSUE THREAD

**Issue by dhslichter** [sinara-hw/Shuttler#16]
@gkasprow if the schematics are ready for review, can you make a PDF to make checking easier?

**Comment by dhslichter** [comment]
Looked with online viewer, seems like there is still more work to be done in some portions before ready for full review.  Closing.

**Comment by gkasprow** [comment]
which portions do you mean? Here are the schematics:
[FMC_DAC_125M_14B_16CHA.PDF](https://github.com/sinara-hw/Shuttler/files/5394527/FMC_DAC_125M_14B_16CHA.PDF)

[FMC_ADC_10B_16CHA_TDC_PSU.PDF](https://github.com/sinara-hw/Shuttler/files/5394525/FMC_ADC_10B_16CHA_TDC_PSU.PDF)
