### ISSUE TITLE
Schematic review: AFE

### ISSUE THREAD

**Issue by dhslichter** [sinara-hw/Shuttler#17]
Overall I think this looks very nice @gkasprow!  Various thoughts below:
- [x] R11, R13 wrong values (A through H)
- [ ] would be good to do SPICE analysis for amplifier noise given resistor values (I can't do all the noise sums in my head).  Optimum source impedance seems to be ~12 kOhm given input voltage and current noise spec.
- [x] Is there any value in splitting the RC terminations (R32, C34; R46, C35) into either R-C-R or C-R-C so they are symmetric with respect to the signal lines?  
- [x] with no voltage regulation on board we are potentially setting ourselves up for large crosstalk because the PSRR of the op-amps is not great above ~100 kHz (50 dB @ 1 MHz, 30 dB @ 10 MHz).  With op-amps potentially driving even 10s of mA of current when running oscillating signals at a few MHz, I don't know if the on-board capacitance is enough to keep the rails from fluctuating substantially.  It also leaves us more open to switch-mode noise that gets on the rails between the power supply and the AFE box.  I would strongly prefer to have LDOs on board (see next comment also).
- [x] LM6172 specs output swings in worst case of +/-12.5 V from +/- 15 V rails (lower for higher current draw, if we are sending MHz signals through).  If we give +/- 12 V rails, it's not clear that we will be able to make the full swing to +/- 10 V for the output.  Might make sense to use +/- 15 V in, with onboard high PSRR @ MHz frequencies LDO to take that down to +/- 13 V or so?  
- [x] P5V0 rail will get a lot of garbage when the relays switch, any concerns there?
- [x] AVDD on the AD4115 needs to be 5 V, per data sheet, not 3.3 V.  This 5 V should not be the same rail as the relays (currently P5V0) because that is a dirty rail.
- [x] there are 16 relay channels but only 8 indicator LEDs?

**Comment by gkasprow** [comment]
I added an LDO for ADC 5V generation. It consumes 10mA of the current total (analog + digital) so LDO will dissipate roughly 80mW

**Comment by gkasprow** [comment]
16 LEDs will fit 
![obraz](https://user-images.githubusercontent.com/4325054/99062046-a817e500-25a2-11eb-8822-38db9fd855b9.png)

**Comment by gkasprow** [comment]
I added 3.3V LDO for LEDs and logic. It's derived from 5V rail.
5V rail is used only for relays and LEDs.

**Comment by gkasprow** [comment]
Let's add LT3045 and LT3094 LDOs generating +/- 13V out of +/- 14..15V

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/99063689-24132c80-25a5-11eb-8304-fd1e970f7bf8.png)

**Comment by gkasprow** [comment]
I don't think that for this frequency range there would be any impact of split termination. But, with the resistor removed, there will be impedance imbalance. One needs to remember to remove or mount both components. I have a place on the PCB so I will add another capacitor to make sure we have a fully balanced pair.

**Comment by dhslichter** [comment]
With LDOs added, do we want to remove the individual ferrites for each op amp?  The ferrites on the LDO inputs should help with any switch-mode spikes from the supplies, but then if we have them between the LDO and the op amps then the LDO can't do as good a job regulating the supplies for higher-frequency signals?  Recall that we may have signals of 10-15 MHz even being generated for some applications.

**Comment by dnadlinger** [comment]
> […] then the LDO can't do as good a job regulating the supplies for higher-frequency signals?

I'd expect any current draw above about 1 MHz to be mainly sourced from decoupling caps, even with the new breed of very nimble LDOs. The low-pass filters formed from ferrites and decoupling caps might help localise any effects from insufficient capacitance, rather than causing more complex crosstalk issues.

**Comment by gkasprow** [comment]
Yes, their role is crosstalk mitigation rather than RF isolation.
For low frequency, they are nearly pure resistance.
