### ISSUE TITLE
[RFC] New AMC: Shuttler (high-speed multi-channel DAC)

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Shuttler#2]
_From @hartytp on [2017-08-16 05:24](https://github.com/sinara-hw/sinara/issues/253)_

I've started sketching out requirements for a fast DAC to be used for ion shuttling/splitting. It's on the [Wiki](https://github.com/m-labs/sinara/wiki/Shuttler).

All comments welcome...

**Comment by tprzywoz** [comment]
Schematics are nearly done so question about AFE: what was the conclusion?
I noted only amplifier parameters: gain 3, supply +/- 2.5 V to give +/- 1.5 V at the output. Is it actual? What are the filter requirements?

**Comment by dhslichter** [comment]
@tprzywoz answered in a new issue (this one is so bloated and long): https://github.com/sinara-hw/Shuttler/issues/3#issue-387849998

**Comment by gkasprow** [comment]
nothing to discuss here, closing
