### ISSUE TITLE
SAS connector availability

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Shuttler#20]
SAS connector given in the project (Molex 75783-0107) is hardly available with MOQ of 750. Though we all hope Shuttler will spread like hot cakes, to make production easier let's change it to 75783-0136.

**Comment by dhslichter** [comment]
As long as this remains compatible with the desired cabling, sounds fine.

**Comment by gkasprow** [comment]
they differ slightly but are pin-compatible
