### ISSUE TITLE
SAS to coax adapter

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Shuttler#21]
To support general applications for Shuttler card, I designed a SAS-to-coax adapter where signals can be easily fanned out without the use of a dedicated AFE
![obraz](https://user-images.githubusercontent.com/4325054/108838826-77e5d680-75d4-11eb-870b-14fa929d1cf8.png)

**Comment by dhslichter** [comment]
hard to tell exactly what's going on here, but cool.  One question -- how do you handle the differential-to-single-ended conversion?

**Comment by gkasprow** [comment]
Just use one output :)

**Comment by dhslichter** [comment]
Fair enough!
