### ISSUE TITLE
FMC PCB review: few points to improve 

### ISSUE THREAD

**Issue by mkiepiela** [sinara-hw/Shuttler#23]
- [x] Add board name and revision number on overlay.

- [x] Add one more via on N3V0A.

![obraz](https://user-images.githubusercontent.com/25741678/114902649-4fc96580-9e16-11eb-910f-84e5843cc424.png)

- [x] Increase the distance between DAC_CLK lines to avoid crosstalk and increasing of sampling clock jitter.

![obraz](https://user-images.githubusercontent.com/25741678/114901584-3b389d80-9e15-11eb-853b-4ac56b54a1d4.png)

**Comment by gkasprow** [comment]
fixed
