### ISSUE TITLE
FMC schematic: DAC_AFE - differential output not inverted?

### ISSUE THREAD

**Issue by mkiepiela** [sinara-hw/Shuttler#25]
DAC_AFE works as inverting amplifier, however differential input and output signals are not inverted (_P/_N marks not swapped). 
Maybe swap output _P/_N lines or at least add some comment on schematic chart, because it can be little misleading.

![obraz](https://user-images.githubusercontent.com/25741678/114947085-c6815580-9e4c-11eb-86cd-039873ea1dac.png)

**Comment by gkasprow** [comment]
good catch :)

**Comment by gkasprow** [comment]
fixed
![obraz](https://user-images.githubusercontent.com/4325054/119221805-65a30800-baf1-11eb-8d15-38219fe2881a.png)
