### ISSUE TITLE
Invalid input circuit for Si53340

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Shuttler#33]
Input circuit arrangement for Si53340 / CLK1 (CLK0 not tested yet, but probably alike) is invalid. Termination resistor should be placed after AC decoupling capacitors. Otherwise Si53340 input bias resistors force P and N lines to have different common mode what results in no output signal.

Moving R21 after C23/C24 solves the issue.

**Comment by gkasprow** [comment]
the same applies to R33
