### ISSUE TITLE
missing decoupling capas at the IC72

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Shuttler#7]
There are FB connected to the supply pins. Aren't there missing decouplig caps?

**Comment by gkasprow** [comment]
can the VOCM be left dangling?

**Comment by dhslichter** [comment]
VOCM for the ADA4927s needs to be tied to ground.

**Comment by tprzywoz** [comment]
> VOCM for the ADA4927s needs to be tied to ground.

Done

> There are FB connected to the supply pins. Aren't there missing decouplig caps?

Added according to datasheet: 1nF 100nF ceramic and 10uF tantalum capacitors for each supply.

**Comment by dhslichter** [comment]
> Added according to datasheet: 1nF 100nF ceramic and 10uF tantalum capacitors for each supply.

Please make notations for voltage and dielectric spec (X7R or NP0) for the ceramic caps.  These amps may be driving a reasonable amount of current into the terminated transmission lines and so we want to make sure we don't have dc bias issues with the capacitors.

**Comment by gkasprow** [comment]
it's not relevant anymore. we don't have any caps in the signal path in the FMC project.
I added a note on the AFE schematics
